### ISSUE TITLE
How to make the history mode work with netlify

### ISSUE THREAD

**Issue by kudapara** [kudapara/paynow-ui#1]
I have discovered that the ```history``` mode used in the vue-router does not work as expected by default on Netlify.

The solution to this problem is suggested by [Netlify's docs](https://www.netlify.com/docs/redirects/#history-pushstate-and-single-page-apps) to use the ```_redirect``` file in the dist folder. However it did not work with the vue build.

So what did the trick was the following stackoverflow answer
```toml
# The following redirect is intended for use with most SPA's that handles routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```
